#设置端口号
server:
  port: 8001

spring:
  application:
    name: cloud-provider-service  #微服务名称，该微服务入驻Eureka的时候在注册中心中的服务名就是这里的微服务名称（就是Eureka注册中心中的服务别名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver        #mysql驱动包
    url: jdbc:mysql://localhost:3306/db2023?useUnicode=true&characterEncoding-utr-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123

eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      # defaultZone: http://eureka7001.com:7001/eureka  单机Eureka：入驻Eureka服务器端的地址
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka  #入驻Eureka集群
  instance:
    instance-id: payment8001 #此配置项作用，在Spring Eureka监控页Status这一栏就显示这个值
    prefer-ip-address: true #添加此处

mybatis:
  mapper-locations: classpath:mapper/*.xml    #xml映射文件
  type-aliases-package: com.swpu.springcloud.entities  #所有Entity别名类所在包
  configuration:
    map-underscore-to-camel-case: true


