server:
  port: 9527

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001         #匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-SERVICE     #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**            # 断言，路径相匹配的进行路由
            #- After=2023-06-06T10:51:37.510+08:00[GMT+08:00]   #这个时间戳之后的请求才会去执行路由
            #- Before=2023-06-06T10:51:37.510+08:00[GMT+08:00]   #这个时间戳之前的请求才会去执行路由
           #- Between2023-06-06T10:51:37.510+08:00[GMT+08:00],2023-06-06T10:51:37.510+08:00[GMT+08:00]  #在这两个时间戳之间的请求才会去执行路由
            - Cookie=username,jwj
        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001           #匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-SERVICE     #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
            - Cookie=username,jwj         # Cookie有两个参数，第一个是key  第二个是value，就是说请求所带的Cookie是否含有key为username，值为jwj的信息
            - Header=RequestId, \d+       # 两个参数：第一个是属性名称，第二个是正则表达式，这个属性值和正则表达式匹配就执行
            - Method=Get                  # 请求方式
