server:
  port: 7001

eureka:
  instance:
    #eureka服务端的实例名称
    hostname: eureka7001.com #在构建Eureka集群的时候，这里不能写localhost，会造成冲突，于是我们先在C:\Windows\System32\drivers\etc路径下的hosts文件中修改配置作一个域名映射，
    # hostname: localhost 单机Eureka设置成localhost
  client:
    #false表示不向注册中心注册自己。
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka server交互的地址,查询服务和注册服务都需要依赖这个地址。 #单机版： defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #defaultZone: http://eureka7002.com:7002/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
